name: When Merged To Main
on:
  pull_request:
    branches:
      - main
    types:
      - closed

  workflow_dispatch:

jobs:
  if_merged:
    name: Test And Build
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_DB_NAME: ${{ secrets.NEXT_PUBLIC_DB_NAME}}@
    steps:
      - name: Download Codes
        uses: actions/checkout@v4

      - name: Install Deps
        run: npm ci

      - name: Test
        run: npm run test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  deploy:
    name: Trigger Deploy Hook
    runs-on: ubuntu-latest
    needs: if_merged
    steps:
      - name: Trigger Deploy Hook
        run: curl -X POST ${{ secrets.DEPLOY_HOOK }}
