name: codecov
on:
  pull_request:
    branches:
      - main
jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Jest
        run: npm install --save-dev jest

      - name: Run Jest
        run: npx jest --coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: wlgns2223/codeit-rtl-todo-fesi8
