name: Context Object
on: [workflow_dispatch, push]
jobs:
  print-context:
    runs-on: ubuntu-latest
    steps:
      #   # repository-name/action-name@version
      #   # 개발환경 vs 프로덕션 환경
      #   # 개발환경 node 22 version
      #   # npm 모듈 -> 자신들이 돌아 갈 수 있는 최적의 버전
      #   # 테스트환경 node 20 version
      #   # 프로덕션환경 node ??

      - name: Install Nodes
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: check node version
        run: node -v

      - name: ls
        run: ls -al

      - name: Print Context
        run: echo "${{toJSON(github)}} "
# echo -> linux에서 로그를 출력하는 명령어

# Context
# 전역적으로 접근이 가능한 변수
# github action에 대한 메타 데이터
# 어떤 레포지토리인가? , 레포지토리 주인이 누구?, 어떤 이벤트에 의해서 트리거가 됐는지?...

# ${{ 변수 }} -> 변수를 사용할 때 사용하는 문법
