name: Conditional Workflow
on:
  push:
    branches:
      - dev
      - main

env:
  NEXT_PUBLIC_API_KEY: ${{ secrets.NEXT_PUBLIC_API_KEY }}

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: 코드 가져오기
        uses: actions/checkout@v4

      - name: 모듈 설치
        run: npm ci

      - name: 테스트
        run: npm run test

      - name: 빌드
        run: npm run build

  lint:
    # 워크플로우를 트리거한 브랜치가 dev일때만 실행
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - name: 코드 가져오기
        uses: actions/checkout@v4

      - name: 모듈 설치
        run: npm ci

      - name: 린트
        run: npm run lint

      - name: 린트 실패시 로그
        run: echo "린트가 실패했습니다."
