name: Conditional Workflow
on:
  push:
    branches:
      - dev
      - main

env:
  NEXT_PUBLIC_API_KEY: ${{ secrets.NEXT_PUBLIC_API_KEY }}

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: 코드 가져오기
        uses: actions/checkout@v4

      - name: 모듈 설치
        run: npm ci

      - name: 테스트
        run: npm run test
        continue-on-error: true

      - name: 빌드
        id: build
        run: npm run build

      - name: 빌드 실패시 로그
        if: failure() && steps.build.outcome == 'failure'
        run: echo "빌드가 실패했습니다."

  lint:
    # 워크플로우를 트리거한 브랜치가 dev일때만 실행
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - name: 코드 가져오기
        uses: actions/checkout@v4

      - name: 모듈 설치
        run: npm ci

      - name: 린트
        run: npm run lint

      - name: 린트 실패시 로그
        # 앞선 단계에서 하나라도 실패를 하면 true를 반환
        if: failure()
        run: echo "린트가 실패했습니다."
