name: Matrix Demo
on: push

env:
  NEXT_PUBLIC_API_KEY: ${{ secrets.NEXT_PUBLIC_API_KEY }}

jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        # node version. 개발자가 사용한 변수. 이름은 마음대로
        # version, node-version, node...
        node-version: [16, 18, 20]

        # os version. 개발자가 사용한 변수. 이름은 마음대로
        # os, os-version...
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{matrix.os }}
    steps:
      - name: 노드 설치
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version}}

      - name: 코드 가져오기
        uses: actions/checkout@v4

      - name: 모듈 설치하기
        run: npm ci

      - name: 빌드 테스트
        run: npm run build
