name: Test, Build, Deploy
on: push
jobs:
  # 1. Test
  # 2. build
  # 3. Deploy -> 콘솔만 남김

  Test:
    runs-on: ubuntu-latest
    steps:
      - name: 코드 가져오기
        uses: actions/checkout@v4

      - name: 모듈 설치하기
        run: npm install

      - name: 테스트 실행하기
        run: npm run test
